import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Image from "next/image";
import Link from "next/link";
import ServicesDropdown from "./components/Services/SerivceDropdown";
import ClientScrollReset from "./components/ClientScrollReset";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Takjas",
  description: "Generated by create next app",

  icons: {
    icon: [
      { url: "/favicons/favicon_16.png", sizes: "16x16", type: "image/png" },   // Web
      { url: "/favicons/favicon_32.png", sizes: "32x32", type: "image/png" },   // Web  
      { url: "/favicons/favicon_96.png", sizes: "96x96", type: "image/png" },   // Web
      { url: "/favicons/favicon_128.png", sizes: "128x128", type: "image/png" },   // Web
      { url: "/favicons/favicon_196.png", sizes: "196x196", type: "image/png" },   // Web

      { url: "/favicons/android-2.png", sizes: "192x192", type: "image/png" }, // Android
      { url: "/favicons/android-1.png", sizes: "512x512", type: "image/png" }, // Android
    ],
    shortcut: ["/favicon.ico"], // Fallback
    apple: [
      { url: "/favicons/apple_57.png", sizes: "57x57" },// iOS
      { url: "/favicons/apple_60.png", sizes: "60x60" },// iOS
      { url: "/favicons/apple_72.png", sizes: "72x72" }, // iOS
      { url: "/favicons/apple_76.png", sizes: "76x76" },// iOS
      { url: "/favicons/apple_114.png", sizes: "114x114" }, // iOS
      { url: "/favicons/apple_144.png", sizes: "144x144" },// iOS
      { url: "/favicons/apple_120.png", sizes: "120x120" }, // iOS
      { url: "/favicons/apple_152.png", sizes: "152x152" }, // iOS
    ],
  },
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <head>
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-square70x70logo" content="/favicons/mstile-70.png" />
         <meta name="msapplication-square144x144logo" content="/favicons/mstile-144.png" />
        <meta name="msapplication-square150x150logo" content="/favicons/mstile-150.png" />
        <meta name="msapplication-wide310x150logo" content="/favicons/mstile-310_150.png" />
        <meta name="msapplication-square310x310logo" content="/favicons/mstile-310.png" />
      </head>


      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* HEADER */}
        <Header />

        <ClientScrollReset>
          {children}
        </ClientScrollReset>


      </body>
    </html>
  );
}
